@startuml
actor User
component NginxGateway

package "service" {
component NginxService
component EchoApp
database PostgresService
}

User -> NginxGateway
NginxGateway -> NginxService
NginxService -> EchoApp
@enduml
