version: "3.8"

services:
  echo-service:
    container_name: echo-service
    image: echo-service
    restart: always
    build: .
    env_file:
      - .env

  nginx-service:
    container_name: nginx-service
    image: nginx:1.25.5
    restart: always
    volumes:
      - ./infra/configs/nginx_service/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/configs/nginx_service/site.conf:/etc/nginx/conf.d/site.conf:ro
    # ports:
    #   - "80:80"

  postgres-service:
    container_name: postgres-service
    restart: always
    image: postgres:14.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${PATH_TO_STORAGE}:/var/lib/postgresql/data
